CREATE TABLE PRODUCTS (
	ID VARCHAR(36) NOT NULL,
	IS_VARIANT_PRODUCT BOOLEAN DEFAULT FALSE,
	ITEM_ID VARCHAR(36) DEFAULT NULL,
	CONSTRAINT PK_PRODUCTS PRIMARY KEY(ID)
);

CREATE TABLE PRICES (
	ID VARCHAR(36) NOT NULL,
	ITEM_ID VARCHAR(36) NOT NULL,
	AMOUNT DECIMAL(12,2) NOT NULL,	
	CURRENCY_CODE VARCHAR(3) NOT NULL,
	CONSTRAINT PK_PRICES PRIMARY KEY(ID),
	CONSTRAINT UC_PRODUCT_ID UNIQUE (ITEM_ID)
);

CREATE TABLE ATTRIBUTES (
	ID VARCHAR(36) NOT NULL,
	ITEM_ID VARCHAR(36) NOT NULL,
	ATTR_KEY VARCHAR(36) NOT NULL,	
	ATTR_VALUE VARCHAR(2048) NOT NULL,
	CONSTRAINT PK_PRODUCT_ATTRIBUTES PRIMARY KEY(ID),
	CONSTRAINT UC_PRODUCT_ATTRIBUTE UNIQUE (ITEM_ID, ATTR_KEY)
);
